[logging]
level = "INFO"
filename='.log'
filemode='a+'
style='{'
format='{asctime} - {levelname} - {message}'
datefmt="%Y-%m-%d %H:%M:%S"

[path]
# Heavy files with geometries for preprocessing and/or validation
batch_dir = "Q:/Data/emdat_geocoding/batch_files" # folder to store the batches
emdat_gaul_path = "Q:/Data/emdat_geocoding/EMDAT_GAUL/geoemdat_gaul.gpkg" # EM-DAT Benchmark
gdis_path = "Q:/Data/emdat_geocoding/GDIS/gdis.gpkg" #  GDIS benchmark or raw data for preprocessing batches
# Ligthweight data without geometries
emdat_archive_path = "data/241204_emdat_archive.xlsx" # doi:10.14428/DVN/I0LTPH
gdis_disno_path = "data/gdis_disnos.csv"
# Output dir
validation_output_dir = "output"

[index]
# keep these colums (i.e., drop 'admin3'), while "geometry_osm",
# "geometry_gadm", "geometry_wiki" are handled separately
llm_columns_to_keep = ["DisNo.", "name", "admin_level", "admin1", "admin2", "iso3"]
llm_geom_columns = ["geometry_osm", "geometry_gadm", "geometry_wiki"]
batch_numbers = [1, 2, 3, 4, 5]

[geoprocessing]
area_calculation_method = 'geodetic' # alternatively 'equal_area'

[validation]
# If true, skip processing a subbatch when its expected output CSV already exists
skip_if_output_exists = false
